"""Generate versioned WebP assets, preserving the original artwork in Git.

Install: python -m pip install -r scripts/requirements-images.txt
Run from any directory: python scripts/optimize-images.py
"""
import hashlib
import io
import json
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
IMAGES = ROOT / 'assets/images'
OUTPUT = IMAGES / 'optimized'
MANIFEST = ROOT / 'assets/image-manifest.json'


def main():
    previous = json.loads(MANIFEST.read_text()) if MANIFEST.exists() else {}
    OUTPUT.mkdir(exist_ok=True)
    manifest = {}
    before = after = 0
    for source in sorted(IMAGES.iterdir()):
        if source.suffix.lower() not in {'.png', '.jpg', '.jpeg'}:
            continue
        with Image.open(source) as original:
            image = ImageOps.exif_transpose(original).convert('RGBA' if 'A' in original.getbands() else 'RGB')
            logo = source.stem.startswith('epav-')
            scene = source.stem.startswith(('escritorio-', 'tela-principal', 'img'))
            longest = 256 if logo else 1920 if scene else 1024
            image.thumbnail((longest, longest), Image.Resampling.LANCZOS)
            budget = (350 if scene else 160) * 1024
            for quality in [84, 78, 72, 66]:
                buffer = io.BytesIO()
                image.save(buffer, 'WEBP', quality=quality, method=6, lossless=logo, exact=True)
                data = buffer.getvalue()
                if len(data) <= budget or logo:
                    break
        digest = hashlib.sha256(data).hexdigest()[:12]
        target = OUTPUT / f'{source.stem}-{digest}.webp'
        target.write_bytes(data)
        manifest[source.name] = target.relative_to(ROOT).as_posix()
        before += source.stat().st_size
        after += len(data)

    # Static backgrounds and HTML use the same URLs as dynamically loaded sprites.
    for filename in ['index.html', 'css/style.css']:
        path = ROOT / filename
        content = path.read_text(encoding='utf-8')
        for name, url in manifest.items():
            if name == 'epav-icone.png' and filename == 'index.html':
                continue  # Apple touch icons retain their compatible PNG format.
            for old in [f'assets/images/{name}', previous.get(name)]:
                if old:
                    content = content.replace(old, url)
        path.write_text(content, encoding='utf-8')
    MANIFEST.write_text(json.dumps(manifest, indent=2) + '\n', encoding='utf-8')
    (ROOT / 'js/image-assets.js').write_text(
        '// Generated by scripts/optimize-images.py.\nwindow.EPAV_IMAGE_ASSETS = Object.freeze('
        + json.dumps(manifest, indent=2) + ');\n', encoding='utf-8')
    print(json.dumps({'images': len(manifest), 'originalMB': round(before / 1024**2, 2),
                      'optimizedMB': round(after / 1024**2, 2),
                      'reductionPercent': round(100 * (1 - after / before), 1)}))


if __name__ == '__main__':
    main()
